[project]
name = "soil-diskin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "rioxarray>=0.19.0",
    "scipy>=1.15.3",
    "xarray>=2025.4.0",
]
