#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2023/09/20 23:15:43
# Search URL: https://esgf-node.llnl.gov/esg-search/wget/?distrib=false&dataset_id=cmip5.output1.MRI.MRI-ESM1.esmFixClim1.mon.land.Lmon.r1i1p1.v20130103|esgf-data01.diasjp.net
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.llnl.gov/esg-search/wget/?distrib=false&dataset_id=cmip5.output1.MRI.MRI-ESM1.esmFixClim1.mon.land.Lmon.r1i1p1.v20130103|esgf-data01.diasjp.net'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'c3PftFrac_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/c3PftFrac/c3PftFrac_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '40a8156c97ba1b70182b21cc3c1ee99acb6a04800c265255b046f51b03f82bbc'
'c4PftFrac_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/c4PftFrac/c4PftFrac_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '5733e3051c622383c0e8083124f9e6d74d707703f4144141815cd0bf9c000335'
'cLeaf_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/cLeaf/cLeaf_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '9f353b7cfd8a305d77bec3c08341fb7f4adf0db5f4450bdc9be9b786776157d1'
'cLitterAbove_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/cLitterAbove/cLitterAbove_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'cc9e663f25a22a859c509243bc1a9c1cfa0b2011b40007ecd3f0a2d4bfc83695'
'cLitterBelow_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/cLitterBelow/cLitterBelow_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '7bf19c2b526afd684651ce08c4ca92cc4f31ca5fb22e749e49a24ab93f6604d9'
'cLitter_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/cLitter/cLitter_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'cb3b8346f7326ce7cee459b2a939d986c130e4a72d01c071424529f416aa3d9d'
'cRoot_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/cRoot/cRoot_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '7d09e440a9db477a613783ad7ad7782e37b3133d457ca25aba522d0f39a82aca'
'cSoilMedium_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/cSoilMedium/cSoilMedium_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'f0141b484b30992bd42041887c05bcc45d50b31de6a4c88b9db2b6cc5e85a4af'
'cSoilSlow_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/cSoilSlow/cSoilSlow_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '12dacc2d9283360c74a95e688a7f8af66f07d31a6c317e5876c9a17d7fe4427b'
'cSoil_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/cSoil/cSoil_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '9128da3e9f3ce491b7a482c2e4a50fbbf98a943de776cbf5af26dfe631ec5bdc'
'cVeg_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/cVeg/cVeg_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'b13fa278ca08ee60f8207b97d06e65eb8a80e8c1a558357e93f7fac57c72be87'
'cWood_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/cWood/cWood_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '4bf62809f6c96f9a438182c22a50a59462bf088b1babfa4a56fc99de7dfe33f0'
'evspsblsoi_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/evspsblsoi/evspsblsoi_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'de2c2aa6f294fba8345fff6ac1c7046f80700b2c92457c5bfec4a5566ec28133'
'evspsblveg_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/evspsblveg/evspsblveg_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '966b70679a333a7a49e9525d712b24d719c1e7c4ac4aa66eded3a06ab3fdf703'
'fFire_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/fFire/fFire_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '513235fd28641d82d5eb5ef2b3fc6c628bd5f91393aefc47f2e37110c779113d'
'fLitterSoil_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/fLitterSoil/fLitterSoil_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '47195cd5e1554a223983bfc0227e5a6e209b15b06a736761e39dbd59515eb5d4'
'fLuc_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/fLuc/fLuc_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'f3183e4efc6acaa3f3d4574aef5290733b928350dc7c9c7eb44264dc3aa459cf'
'fVegLitter_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/fVegLitter/fVegLitter_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '20de9374c72a0bdd2490c15635188af8604ef833f387659c2a9f93f036852cbb'
'gpp_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/gpp/gpp_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'a532bf6dab9d46fde0a6d7fabbd1b9d497ca105e0fca4af1bc8303c256be7d3d'
'lai_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/lai/lai_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '5272db5aa529dbec49144943f6a22f0cee672ea803cc47f92a149d178cf1d1f5'
'landCoverFrac_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/landCoverFrac/landCoverFrac_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'a57682ba8f806bcf7faa3b7574d5892d0f388a4cfc6a074f29882265ad8dd0e9'
'mrfso_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/mrfso/mrfso_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '7619ccccdf2df65ac3d88dd3e1e677bbaacdce4d0c70703047b19409064f0a6e'
'mrro_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/mrro/mrro_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '1d4c88e24bf5d6118dd5d631c871ac3438f042af71adc4405433a1837e5d682c'
'mrros_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/mrros/mrros_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '4e8cde0d836ab76343dbfec80c2dc3a01da062fee10c610d954b7013a8663bdf'
'mrso_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/mrso/mrso_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '9da6c9152a86aa92c89e7b84f819a4b72372ebac713abdab962d5125c6ed4fdc'
'mrsos_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/mrsos/mrsos_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'acd43081d983cdc97237090359de612b037394bf0996e9080ec8b4506308c430'
'nbp_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/nbp/nbp_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '532bc96d48f246e7dec53a778a836840623ab38ce2ca964d4ea1f832fb795ffe'
'nep_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/nep/nep_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '66c095dcfe0cf8cd018b2764a48af681d4fb0846d8eb1be189823367817b59de'
'nppLeaf_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/nppLeaf/nppLeaf_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '8f923018aa794ed32825819fc863d9d05bfcf747ca140f7d258079bc8ecb2bee'
'nppRoot_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/nppRoot/nppRoot_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'ef5048c6ae76ab47af0c5c210f05328f519d2648669295fe0efeeebcfb90b152'
'nppWood_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/nppWood/nppWood_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '341e6f5aefd27708b50ea50b1d25dcfbd0ba2f4416e7f5157bee1a1877b03818'
'npp_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/npp/npp_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '96db33e3a1b27c8e0e0674154e691d6b812617b989e3d7feca0ee432c9e3683a'
'rGrowth_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/rGrowth/rGrowth_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '63c37e81a821f6c35ccdbb8ef291591a67ddec7e346e88fceda4a464aa13ff59'
'rMaint_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/rMaint/rMaint_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'a78827e0866a2fd97734c440a8a1731db4b8b96b34c972b7ec24e716f7772db4'
'ra_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/ra/ra_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '5bdc778323c3766d0f0d625bcbd762982bb4914b5db536b705e3544f38539624'
'rh_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/rh/rh_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' '15a03bfff0c1e9e744efe57aee89c37381858b590323194f66c42370c748f7e3'
'tran_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tran/tran_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-200012.nc' 'SHA256' 'd77a041bef3757ef4b3d0000d7d2e5ed984c6d2dd139dacbf1359bf00a40be7e'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-186012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_185101-186012.nc' 'SHA256' 'a2fc8b780002ecb955d0f2c84ffcd879b6de45a9faf3b9b664eecdfcdd55d0f1'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_186101-187012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_186101-187012.nc' 'SHA256' '9fbb74ab24d46c8e40d4144c214367a477c4cf737da2013844f05034c9c467f5'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_187101-188012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_187101-188012.nc' 'SHA256' '351d06341c20148e053200d71750986dfb7ca018d5b83ab66db54342e229473b'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_188101-189012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_188101-189012.nc' 'SHA256' '54ed373a23f12cecf1f31128cc8ff919f5908d6228d956cc788ad804018b6d28'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_189101-190012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_189101-190012.nc' 'SHA256' 'a93a1ef91a34809ee00c26577175da64c5f68c5d2af712b898240bd92210bcab'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_190101-191012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_190101-191012.nc' 'SHA256' 'a196e970900fe574addff26cacf182bec43c9453a48114f599f71945a1952168'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_191101-192012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_191101-192012.nc' 'SHA256' '95003f436c92e1e70f7f1c8f856704bf99583657121a5e714944354ce9f36f42'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_192101-193012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_192101-193012.nc' 'SHA256' 'a721c3178b6760052aaa2a35145208b0b67e3e7cc4f458c0a0dbe3b6e82dd4e5'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_193101-194012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_193101-194012.nc' 'SHA256' 'e3eae8d30add79db9be53563f542a814bdc481f242183083acb00ac30c30c16a'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_194101-195012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_194101-195012.nc' 'SHA256' '1e8839a2266fbf150e4eb89f862e7aea9b6f9fa802b9105e61377785a270ce85'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_195101-196012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_195101-196012.nc' 'SHA256' '6af94a2422215bcb922b92a59f4145b99b285a7ccbb00834687484b05b93a738'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_196101-197012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_196101-197012.nc' 'SHA256' 'e128d0fa63ce419d9061a354a4a96f1758fb3251b5b31836ba99883371d74322'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_197101-198012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_197101-198012.nc' 'SHA256' '568bcd2c3dbefc627c7c930f39677122b36c8e9e777c9c097a444de2c6a1f144'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_198101-199012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_198101-199012.nc' 'SHA256' '3be9b05cf30097834a7fa132ba958f7821b41373ceb6705d9e7112b4bd5b90ad'
'tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_199101-200012.nc' 'http://esgf-data01.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/esmFixClim1/mon/land/Lmon/r1i1p1/v20130103/tsl/tsl_Lmon_MRI-ESM1_esmFixClim1_r1i1p1_199101-200012.nc' 'SHA256' '5ee1c86a4d6a11320cc7d89578bfab773865d9db6bd6c521b2d552e569c375a0'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 52 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
