using Pkg
using CSV
using DataFrames
using ProgressBars

Pkg.instantiate()

include("diskin_utils.jl")

# The file below is generated by notebooks/03b_calibrate_lognormal_model.py
ages = CSV.read("results/06_sensitivity_analysis/lognormal_age_predictions.csv", DataFrame); 
turnover = CSV.read("results/all_sites_14C_turnover.csv", DataFrame);
tmax = 100_000; # maximum time for the ODE solution
ts_size = 1000; # size of the time series
ts = 10 .^ range(-1,log10(tmax),ts_size);
# create a matrix the size of the number of rows in params and with 100_000 columns
results = Matrix{Float64}(undef, size(ages, 1), ts_size);
colnames = names(ages)
for j in 1:size(ages, 2)
    for i in ProgressBar(1:size(ages, 1))
            # run the diskin model for each row in params
            # results[i,:] = run_diskin(params[i,:turnover], params[i,:pred], 1, true, tmax, ts_size);
        result = run_diskin(turnover[i,:turnover], ages[i,j],1, true, tmax, ts_size);
        results[i,:] = reduce(vcat, result);
        
    end
    CSV.write("results/06_sensitivity_analysis/06a_lognormal_cdfs_" * colnames[j] * ".csv",  Tables.table(results, header = ts));
end

# @btime cont = run_diskin(17,1000,0.25,true,false);
# @btime noncont = run_diskin(17,1000,0.25,true,true);
# cont'./noncont